### ISSUE TITLE
Failed opening required '../vendor/autoload.php'

### ISSUE THREAD

**Issue by avh4** [svanderburg/composer2nix#5] opened 2018-10-13 06:45 UTC
Running `composer2nix` fails on line 3, apparently because it is trying to look in `<composer dir>/vendor/svanderburg/composer2nix/vendor/autoload.php` when it should instead be looking in `<composer dir>/vendor/autoload.php`

```
$ composer global require svanderburg/composer2nix
Changed current directory to /Users/avh4/.composer
Using version ^0.0.3 for svanderburg/composer2nix
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing svanderburg/pndp (v0.0.2): Downloading (100%)
  - Installing svanderburg/composer2nix (v0.0.3): Downloading (100%)
Writing lock file
Generating autoload files
$ ~/.composer/vendor/bin/composer2nix -p phpunit/phpunit

Warning: require_once(/Users/avh4/.composer/vendor/svanderburg/composer2nix/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/avh4/.composer/vendor/svanderburg/composer2nix/bin/composer2nix on line 3

Fatal error: require_once(): Failed opening required '/Users/avh4/.composer/vendor/svanderburg/composer2nix/bin/../vendor/autoload.php' (include_path='.:') in /Users/avh4/.composer/vendor/svanderburg/composer2nix/bin/composer2nix on line 3
```

**Comment by svanderburg** [comment] 2020-03-14 22:45
I merged the corresponding PR. Since the root cause is fixed, this can be closed.

**Closed by svanderburg** 2020-03-14 22:45 UTC
